# Generated by Django 5.2.4 on 2025-09-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="modified_at",
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["-created_at"], name="journal_jou_created_b6c001_idx"
            ),
        ),
    ]
