# Generated by Django 5.2.4 on 2025-08-24 13:13

import src.apps.notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="timestamp_id",
            field=models.CharField(
                default=src.apps.notes.models.generate_timestamp, max_length=14
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
